# Where should we write the GIF?
Output texts.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 20
Set Width 1200
Set Height 600

# Type a command in the terminal.
Type "odin run ."

# Pause for dramatic effect...
Sleep 500ms

# Run the command by pressing enter.
Enter

# Wait for text display to load
Sleep 3s

# The text demo is mostly static, showing different text styles
# Just wait to show the output

Sleep 3s

# Admire the output for a bit.
Sleep 3s
