# Where should we write the GIF?
Output counter.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 20
Set Width 1200
Set Height 600

# Type a command in the terminal.
Type "odin run ."

# Pause for dramatic effect...
Sleep 500ms

# Run the command by pressing enter.
Enter

Sleep 2s

Space
Sleep 1s

Space
Sleep 1s

Space
Sleep 1s

Type "d"
Sleep 1s

Type "d"


# Admire the output for a bit.
Sleep 3s
